### ISSUE TITLE
Demo doesn't log in

### ISSUE THREAD

**Issue by Sylk** [mbezhanov/vuejs-rest-client-example#1]
I tried the demo of this and the post request it kept sending was options, and never logged in.

**Comment by mbezhanov** [comment]
Hello @Sylk, and thank you for reporting this issue.

The demo did not work for you, because I stopped the underlying back-end services some time ago. I've just restarted them, so you can try the app out.

However, do keep in mind - this is code I wrote as a quick demo. It is simplified, and I wouldn't use code like this in production. Especially the way authentication is implemented is far from ideal.

Feel free to re-open the issue if you notice any other problems.
